
# Attention
# This is a testing script. There is no validation of configuration parameters yet!

cratedb:
  host: 127.0.0.1
  port: 4200

mysql:
  host: 127.0.0.1
  port: 3306
  username: username
  password: password

elasticsearch:
  host: 127.0.0.1
  port: 9200

graphite:
  host: 127.0.0.1
  port: 2003

#Fake check result values
#check_interval in minutes
check_interval: 1

# Days you want to generate performance data for
days: 90


